language: python
env:
  - TOXENV=py26-test
  - TOXENV=py27-test
  - TOXENV=py27-lint
  - TOXENV=py34-test
  - TOXENV=py34-lint
  - TOXENV=py35-test
  - TOXENV=py35-lint
  - TOXENV=docs
install:
  - pip install tox
script:
  - tox
